apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  labels:
    app: crossplane
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: crossplane
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: control-provider
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.19.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
