apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-family-gcp-config
  annotations:
    helm.sh/hook-weight: "1"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-family-gcp-config
      key: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: provider-family-gcp-config
  namespace: crossplane-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: scaleway
    kind: ClusterSecretStore
  target:
    name: provider-family-gcp-config
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: name:family-gcp-token-sync
